#!/bin/bash

# A bash script for awesomeness

version_number=0.1.0

about() {
	mitchell_logo
	echo 'awesomeness'
}

beer() {
	echo 'beer'
}

fun() {
	#FILENAME = 'file.txt'
	
	echo -n "Enter your name and press [ENTER]: "
	read name
	
	#echo "Welcome $name"
	
	echo -n "Can we store your information? [y/n] "
	read store
	
	if [ $store == "y" ]; then
		echo "Storing data..."
		echo $name >> file.txt
	else 
		echo "Bummer"
	fi
	
	echo -n "Would you like to see our friends? [y/n]"
	read friends
	
	if [ $friends == "y" ]; then
		echo "Our Friends:"
		
		while read line           
		do           
		    echo -e "$line"           
		done < file.txt  
	else 
		echo "Thanks for nothing!"
	fi	
}

help() {
	cat <<HELP
	
	OPTIONS:
		--help
		--version
	
HELP
}

startup_add() {
	dir=`dirname $0`
	file="$dir/_startup.txt"

	echo	
	echo -n "Enter your App Name: "
	read name

	echo -n "Enter your App Path: "
	read path
	
	if [ "$name" == "" ] || [ "$path" == "" ]; then
		echo "One of your inputs was blank. Please try again."
	else
		echo "Storing data..."
		echo "$name | $path" >> $file
		echo
		echo 'Startup Updated!'
	fi
}

startup_read() {
	dir=`dirname $0`
	startupfile="$dir/_startup.txt"

	echo

	declare -a appslist
	declare -a apps
	let i=0
	while IFS='\n' read -r line_data; do
		IFS='| ' read -r -a array <<< ${line_data} # split our line by the pipe (|)
		
		apps[i]="${array[0]}"
		appslist[i]="${array[1]}"
		((++i))		
	done < $startupfile

	printf "${apps}"
	echo
	printf "${appslist}"
	echo
}

show_commands() {
	echo "COMMANDS"
}

version() {
	mitchell_logo
	echo "mitchell version $version_number"
}

check_args() {
	if [ ! -z "$1" ]; then 
		"$1"
	fi
}

mitchell_logo() {
	cat <<MITCHELLTEXT
  __  __ _ _       _          _ _ 
 |  \/  (_) |_ ___| |__   ___| | |
 | |\/| | | __/ __| '_ \ / _ \ | |
 | |  | | | || (__| | | |  __/ | |
 |_|  |_|_|\__\___|_| |_|\___|_|_|

MITCHELLTEXT
}

main() {                          
	check_args "$@"
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
	main "$@"
fi